site_description: Test blog site
site_name: My Docs
site_url: https://mkdocs-demo-3sc.pages.dev/
theme:
  font:
    code: Roboto Mono
  language: ja
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: subako-light 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: subako-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  features:
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: YYYY年MM月
      categories_allowed:
        - Holidays
        - News
      pagination_per_page: 5
  - tags

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Blog:
     - blog/index.md
     - Tags: blog/tags.md

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk

hooks:
  - hooks/socialmedia.py
